### ISSUE TITLE
`tracksubject` feature is ambiguous

### ISSUE THREAD

**Issue by JoanneHing** [AY2425S1-CS2103T-W11-3/tp#171]
Using `tracksubject` with complete list
<img width="728" alt="Screenshot 2024-10-31 at 2 42 43 AM" src="https://github.com/user-attachments/assets/e6a899ca-c451-4298-a7d2-b76e9e938649">

Using `tracksubject` after `find` command
<img width="730" alt="Screenshot 2024-10-31 at 2 41 42 AM" src="https://github.com/user-attachments/assets/3a61dffd-a974-4025-85d4-ef27c9ccc5cb">

Using `tracksubject` after `filter` command
<img width="737" alt="Screenshot 2024-10-31 at 2 43 46 AM" src="https://github.com/user-attachments/assets/febb73e7-098d-4b91-b46c-346cc31f4bd3">

When we use `find` or `filter` command first before `tracksubject`, the `tracksubject` window will only display the subject statistic based on the filtered list, but not the overall subject taken. Is this an intended behaviour ? Should the `tracksubject` should always display overall enrolment statistic or based on the filtered one?

**Comment by JoanneHing** [comment]
I think for this we could specify that the track subject display the subject statistic based on the filtered list so user can do filter year 2 student, and see the enrolment for the subject taken by year 2 students, just that we need to mention this in the UG

**Comment by adriantan101** [comment]
Got it! Will modify this in the UG before submission
