### ISSUE TITLE
Suggestion for adding keyboard shortcut to exit subject statistics window

### ISSUE THREAD

**Issue by cweijin** [AY2425S1-CS2103T-W11-3/tp#189]
Might be helpful to have keyboard shortcut to close the subject statistics window, as to align with tP's typing-preferred constraint. 

![image](https://github.com/user-attachments/assets/1c744ab3-cd17-4d6a-8f9a-7ad0365f90b5)

**Comment by adriantan101** [comment]
Keyboard shortcut already added.
