### ISSUE TITLE
Message Displayed for `StudentID` should be not found rather than invalid

### ISSUE THREAD

**Issue by JoanneHing** [AY2425S1-CS2103T-W11-3/tp#192]
<img width="849" alt="Screenshot 2024-11-03 at 1 16 28 AM" src="https://github.com/user-attachments/assets/d20a8b25-3873-4abc-9afe-acf23b2e0d98">

This `StudentID` should be in valid form? Or Maybe the error message could say the number should start with 00001 and maximum is 99999?

**Comment by cweijin** [comment]
Ok will fix the error message
