### ISSUE TITLE
[PE-D][Tester A] New JAR file includes existing contacts

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W11-3/tp#283]
Especially in the case of this app, which includes Student Numbers that are non-replaceable, having existing students whose student number cannot be replaced when deleted is a flaw. For eg, Alex Yeoh is pre registered in the JAR file. If I were to delete his information, S0001 still would not be able to be used even after deletion.

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: Jalenleeruixian/ped#3

**Comment by JoanneHing** [comment]
In user guide, mention that we have some dummy data. We recommend user to use these data to play around and familiarize themself with the commands then use `clear` to reset the address book.
