### ISSUE TITLE
[PE-D][Tester A] No specific ordering for subject statistics

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W11-3/tp#286]
There is no specific ordering for subject statistics, and no way to select a preference as well. This makes it confusing especially when the number of subjects is high.
![Screenshot 2024-11-08 at 4.25.29 PM.png](https://raw.githubusercontent.com/Jalenleeruixian/ped/main/files/8a445af0-55f5-4591-a56f-5a516551041d.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Jalenleeruixian/ped#4

**Comment by JoanneHing** [comment]
I think this should actually be an cosmetic issue, but could mention this as enhancement to sort it so it easier to read .
