### ISSUE TITLE
[PE-D][Tester A] Invalid email accepted

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W11-3/tp#288]
Invalid emails, such as ones having mulitple .coms, can be accepted.
![Screenshot 2024-11-08 at 4.56.21 PM.png](https://raw.githubusercontent.com/Jalenleeruixian/ped/main/files/a8478306-7530-4f84-90ad-9ee16a165e5e.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Jalenleeruixian/ped#6

**Comment by JoanneHing** [comment]
this is valid email format.
But in UG is not detailed described. Could update that.
