### ISSUE TITLE
[PE-D][Tester B] Absence of deletesubject command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W11-3/tp#332]
Since there is an addsubject command, I think there should be a deletesubject command, because users may input a wrong subject accidentally due to various reasons, and then there is no way to delete that subject, not even in Edit. Thus users will have to delete that student altogether along with other information and retype it all over again. 

![image.png](https://raw.githubusercontent.com/kaikquah/ped/main/files/3e98c331-f7ec-4682-9048-9416e7d0a6c1.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: kaikquah/ped#22

**Comment by annabellekk** [comment]
We can argue that this is actually possible to do with edit? Slightly confused why the tester believes that edit can't remove the subject. But I can add deletesubject as planned enhancement in DG
